# .github/workflows/deploy.yml
name: Deploy main branch
on:
  push:
    branches:
      - main
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup node env
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          check-latest: true
      - name: Checkout
        run: |
          npm install
          npm run build -- --base /${{ github.event.repository.name }}/
          touch .vitepress/dist/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          folder: .vitepress/dist/
          branch: gh-pages
          clean-exclude: pr-preview